sylius_resource:
    resources:
        app.supplier:
            classes:
                model: App\Entity\Supplier
                form: App\Form\Type\SupplierType
        
        app.storagelocation:
            classes:
                model: App\Entity\StorageLocation
                
