sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: /admin

app_supplier:
    resource: |
        alias: app.supplier
        except: ['show']
        section: admin
        templates: "@SyliusAdmin\\Crud"
        grid: app_admin_supplier
    type: sylius.resource
    prefix: /admin

sylius_paypal_admin:
    resource: "@SyliusPayPalPlugin/Resources/config/admin_routing.yml"
    prefix: /admin
